# MD010/no-hard-tabs - Hard tabs
MD010:
  # Include code blocks
  code_blocks: false

MD013: false

MD024:
  # Only check sibling headings
  allow_different_nesting: true
  # Only check sibling headings
  siblings_only: true

MD033:
  # Allowed elements
  allowed_elements:
    - img

# MD037/no-space-in-emphasis - Spaces inside emphasis markers
MD037: false
