name: PR Validation

on: pull_request

jobs:
  build:
    name: markdownlint-cli
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install markdownlint-cli
      - run: make markdownlint
