name: PR Validate
on: pull_request
jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@0.16.0
  markdownlint:
    name: markdownlint-cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install markdownlint
        run: npm install markdownlint-cli
      - name: Run markdownlint
        run: make markdownlint
