name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Generate docs
        run: |
          make gh-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
