name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Remote repository name that triggered workflow'     
        required: true

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/node@v1
      - name: Install dependencies
        run: |
          make install-site
      - name: Generate docs
        run: |
          make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated/site
