name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Remote repository name that triggered workflow'     
        required: true
  schedule:
    - cron:  '0 7-18 * * 1-5'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Sync repos
        run: |
          set -e
          node .github/workflows/sync-docs.js terraform-modules "Terraform Modules" modules
          node .github/workflows/sync-docs.js azure-devops-templates "Azure DevOps Templates"
      - name: Test Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
