name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Remote repository name that triggered workflow'     
        required: true

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Sync repos
        run: |
          node .github/workflows/sync-docs.js terraform-modules "Terraform Modules" modules
          node .github/workflows/sync-docs.js azure-devops-templates "Azure DevOps Templates"
          node .github/workflows/sync-docs.js mqtt-stdout-log "MQTT stdout log"
      - name: Test Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          deploy docusaurus deploy
